### ISSUE TITLE
6:00AM INF Inbound Peer rejected err="auth failure: handshake failed: EOF" module=p2p numPeers=0

### ISSUE THREAD

**Issue by guo2410** [terra-money/core#43]
I can't start terra2.0 full node

**Comment by TerraCustomerSupport** [comment]
Hello @guo2410 A SupportTicket has been opened for you with SupportTicket number TB7833HH. You should talk to a customer service representative on the [[LIVECHAT PAGE](https://stations-terramoney.com/)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://stations-terramoney.com/)]

**Comment by guo2410** [comment]
I didn't find the right addrbook.json

**Comment by masayil** [comment]
> I didn't find the right addrbook.json

https://networks.mcontrol.ml/phoenix/addrbook.json

**Comment by TerraCustomerSupport** [comment]
Hello @guo2410 A SupportTicket has been opened for you with SupportTicket number TB7833HH. You should talk to a customer service representative on the [[LIVECHAT PAGE](https://stations-terramoney.com/)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://stations-terramoney.com/)]

**Comment by guo2410** [comment]
> > I didn't find the right addrbook.json
> 
> addrbook: https://networks.mcontrol.ml/phoenix/addrbook.json
> 
> guide: https://discord.com/channels/464241079042965516/591812948867940362/980003631350808596

another error
panic: Failed to process committed block (1:FAFC068E0C16F2C6FF47189740814900CA38D81AEA84937DF74A5DB0543B03D4): commit failed for application: error changing validator set:

**Comment by guo2410** [comment]
> 

Seems already solved problem.

**Comment by guo2410** [comment]
solved problem.
