### ISSUE TITLE
[BUG] terracli broken in tag v0.5.0-rc0?

### ISSUE THREAD

**Issue by sveilleux1** [terra-money/core#514]
**Describe the bug**
On tag `v0.5.0-rc0` most command issued with terracli on the local terrad node are failing with 'ERROR: ABCIQuery: error unmarshalling result: unknown field "proofOps" in types.ResponseQuery '

**To Reproduce**
- git checkout  v0.5.0-rc0
- run `make install`
- copy lastest localterra repo config folder to ${HOME}/.terra/config
- run `terrad unsafe-reset-all`
- run `terrad start`
- on another window, try to use terracli with, for example, `terracli query staking validators`
- it's failing with the ABCIQuery error mentioned before

**Context & versions**
- core tag  v0.5.0-rc0
- terrad config from localterra main branch config folder
- terracli version is `0.4.6-5-g5860232`
- terrad version is `0.5.0-rc0`

**Comment by 0xlarry** [comment]
`terracli`'s functionalities are merged into `terrad` afaik. If you build on tag `v0.5.0-rc2` it should not even generate a `terracli` executable. The `terracli` executable you're running is probably leftover from a previous build.

**Comment by sveilleux1** [comment]
Good to know!

I think the developer doc should be updated to mention using terrad instead of terracli.

Also, the lastest localterra docker-compose is using a bombay terra node image that include terracli. And running terracli inside the image produce the same issue.

**Comment by tcrognon** [comment]
I have this same problem on master. I followed the tutorial (https://docs.terra.money/contracts/tutorial/) exactly and can't get past this part:
```
~/my-first-contract/artifacts$ terracli tx wasm store my_first_contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block
Enter keyring passphrase:
ERROR: ABCIQuery: error unmarshalling result: unknown field "proofOps" in types.ResponseQuery
```
I'm guessing it's because
- this repo is using tendermint 0.33.9 (https://github.com/terra-money/core/blob/58602320d2907814cfccdf43e9679468bb4bd8d3/go.mod#L20)
- there was a breaking change from 0.33.9 to 0.34.0 in tendermint (https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md#v0340 https://github.com/tendermint/tendermint/pull/4989)
- ??? rust-optimizer assumes tendermint >= 0.34.0 (this is my first day trying terra, so apologies if that doesn't make any sense)

I tried using older versions of rust-optimizers, but I couldn't get it working.

**Comment by sveilleux1** [comment]
you need to be using localterra v0.4.1
```
git clone --branch v0.4.1 --depth 1 https://github.com/terra-money/localterra.git
``` 

since localterra master is already using bombay (colombus-5) the remaining of the tutorial seems to be incompatible with it.
I'm submitting a PR for the doc about this issue.

**Comment by tcrognon** [comment]
Thank you, using localterra v0.4.1 worked.

**Comment by ilovejs** [comment]
you hv 20 contributor but 50 tags incl breaking changes ?!! @YunSuk-Yeo
