### ISSUE TITLE
[question] Is there other way to get 'terracli' ?

### ISSUE THREAD

**Issue by paulvi** [terra-money/core#527]
Is there other way to get 'terracli' ?

**Comment by YunSuk-Yeo** [comment]
@paulvi 
after bumping to cosmos-sdk to v0.43, no more client binary supplied. 

all commands in terracli moved to terrad.

you can use terrad as like terracli

**Comment by gbjk** [comment]
I think you need to actually say that in the [documentation](https://docs.terra.money/terracli/) 🙂 

Nothing in the github repo, source or the docs makes it clear, and I spent a while looking for how to build it before finding this 
issue.

Since this issue is closed, it doesn't come up by default, either.
